version: "3"
services:
  mysql:
    container_name: db-mysql
    image: mysql/mysql-server:8.0
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Seoul
    volumes:
      - mysql-data:/var/lib/mysql
    command:
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    ports:
      - '3306:3306'
    expose:
      - "3306"
    networks:
      - app-tier
  database-adminer:
    container_name: db-adminer
    image: adminer:latest
    ports:
      - "18080:8080"
    environment:
      - ADMINER_DEFAULT_SERVER=db-mysql
      - ADMINER_DESIGN=hydra
      - ADMINER_PLUGINS=tables-filter tinymce
    networks:
      - app-tier
  frontend:
    container_name: frontend-react
    build:
      context: ./frontend
    environment:
      - REACT_APP_BACKEND_URL= http://localhost
    volumes:
      - ./frontend/:/frontend
      - build_folder:/frontend/build
      - ./frontend/node_modules/:/frontend/node_modules
    networks:
      - app-tier
    stdin_open: true
    tty: true
    expose:
      - "3000"
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      #docker-compose.yml과 같은 레벨에 둔 nginx.conf를 mount.
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
      - frontend
    expose:
      - 80
    restart: always
    networks:
      - app-tier
  backend:
    container_name: api-server
    build: ./backend/
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db-mysql:3306/voilio
      SPRING_DATASOURCE_USERNAME: ${MYSQL_USER}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    expose:
      - "8080"
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge
volumes:
  mysql-data:
  build_folder: